# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'
 modules_path = '../../../node_modules'
 react_native_path = modules_path + '/react-native'
target 'ICE20' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for ICE20
  # Required by RNFirebase
 pod 'Firebase/Core', '~> 6.3.0'
 pod 'Firebase/Auth', '~> 6.3.0'
 pod 'Firebase/Firestore', '~> 6.3.0'
 pod 'Firebase/Functions', '~> 6.3.0'
 pod 'Firebase/Storage', '~> 6.3.0'
 
 #pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  #pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'ViroKit_static_lib', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/static_lib'

  target 'ICE20Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ICE20-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ICE20-tvOS

  target 'ICE20-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
